// app/api/suggestions/route.ts

import { NextResponse } from "next/server"

export async function POST(request: Request) {
  try {
    const { prompt, productId } = await request.json()

    if (!prompt) {
      return NextResponse.json(
        { error: "Prompt is required" },
        { status: 400 }
      )
    }

    // Use real Gemini AI
    const suggestions = await getGeminiSuggestions(prompt, productId)
    
    return NextResponse.json(suggestions)
    
  } catch (error) {
    console.error("AI Suggestions Error:", error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Failed to generate suggestions" },
      { status: 500 }
    )
  }
}

async function getGeminiSuggestions(prompt: string, productId: string): Promise<any> {
  const GEMINI_API_KEY = process.env.GEMINI_API_KEY
  
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured. Please add it to your .env.local file.")
  }

  try {
    const response = await fetch(
      
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: `You are a professional sneaker designer. Based on this prompt: "${prompt}", create a complete sneaker customization.

Respond with ONLY valid JSON (no markdown, no explanation outside JSON, no code blocks):

{
  "explanation": "A brief 1-2 sentence description of the design concept",
  "sole": {"color": "#HEXCODE", "material": "leather|canvas|mesh|suede"},
  "upper": {"color": "#HEXCODE", "material": "leather|canvas|mesh|suede"},
  "laces": {"color": "#HEXCODE", "material": "leather|canvas|mesh|suede"},
  "swoosh": {"color": "#HEXCODE", "material": "leather|canvas|mesh|suede"},
  "text": "SHORT_TEXT"
}

Requirements:
- Use real hex color codes (e.g., #FF0000 for red, #0000FF for blue)
- Keep text under 10 characters
- Choose materials from: leather, canvas, mesh, or suede
- Make colors harmonious and stylish
- Ensure the design matches the prompt's theme/mood

IMPORTANT: Return ONLY the JSON object, no markdown formatting, no backticks.`
            }]
          }]
        })
      }
    )

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(`Gemini API error: ${response.status} - ${JSON.stringify(errorData)}`)
    }

    const data = await response.json()
    
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("No suggestions generated by AI")
    }
    
    const text = data.candidates[0].content.parts[0].text
    
    // Clean up the response - remove markdown code blocks if present
    let cleanedText = text.trim()
    cleanedText = cleanedText.replace(/```json\n?/g, '')
    cleanedText = cleanedText.replace(/```\n?/g, '')
    cleanedText = cleanedText.trim()
    
    // Extract JSON from response
    const jsonMatch = cleanedText.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
      throw new Error("Could not find valid JSON in AI response")
    }
    
    const parsed = JSON.parse(jsonMatch[0])
    
    // Validate the response has required fields
    if (!parsed.explanation || !parsed.sole || !parsed.upper || !parsed.laces || !parsed.swoosh) {
      throw new Error("AI response missing required fields")
    }
    
    return parsed
    
  } catch (error) {
    console.error("Gemini API Error:", error)
    throw error
  }
}